version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.3.6  # Указываем точную версию
        environment:
          BUNDLE_PATH: "vendor/bundle"
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y build-essential
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec

  lint:
    docker:
      - image: cimg/ruby:3.3.6  # Тоже указываем 3.3.6
    steps:
      - checkout
      - run: gem install rubocop
      - run: rubocop

workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint
      - test
