version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.3.6
        environment:
          BUNDLE_PATH: "vendor/bundle"

jobs:
  test:
    executor: ruby-executor
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y build-essential
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec

  lint:
    executor: ruby-executor
    steps:
      - checkout
      - run: gem install rubocop
      - run: rubocop

workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint
      - test
